from _typeshed import Incomplete

def check_access(file_path, access_type): ...
def get_files(path, include_pattern: Incomplete | None = ..., exclude_patterns: Incomplete | None = ..., max_depth: int = ..., follow_symlinks: bool = ..., access_type: str = ...): ...
def format_output(result, output_format): ...
def pretty_print_json(data) -> None: ...
def main() -> None: ...
